version: 2

jobs:
  test:
    docker:
      - image: cimg/node:20.19.6
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

      - run: yarn lint --no-fix
      - run: yarn lint:style

      # Jest performance notes:
      # https://discuss.circleci.com/t/babel-7-jest-results-in-timeout/25383
      # https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
      - run: yarn test:unit --coverage --coverageReporters html --runInBand

      - store_artifacts:
          path: coverage/

  deploy:
    docker:
      - image: cimg/node:20.19.6
    steps:
      - attach_workspace:
          at: /home/circleci

      - run: yarn build:demo

      - add_ssh_keys:
          fingerprints:
            - "SHA256:OABKueezBmBHbO8cjcj8AEqEGTHtzsXNofOJSK6fJgQ"

      - deploy:
          command: .circleci/pages-deploy.sh

  publish:
    docker:
      - image: cimg/node:20.19.6
    steps:
      - attach_workspace:
          at: /home/circleci

      - run: yarn build

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc

      - add_ssh_keys:
          fingerprints:
            - "SHA256:OABKueezBmBHbO8cjcj8AEqEGTHtzsXNofOJSK6fJgQ"

      - deploy:
          name: Publish package
          shell: bash
          command: .circleci/npmjs-publish.sh

workflows:
  version: 2
  checkout_test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
